name: Keep Branch in Sync with Main

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 * * * *" # Optional: hourly sync

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Verify Python version
        run: python --version

      - name: Create virtual environment with Python 3.10
        run: |
          python3.10 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Merge main into current branch
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git fetch origin main
          git checkout ${{ github.ref_name }}
          git merge origin/main || echo "Already up to date"

      - name: Push changes if merge occurred
        run: |
          git push origin HEAD || echo "No changes to push"

      - name: Run project setup script (optional)
        run: bash setup/setup.sh
